### ISSUE TITLE
Kernel Panic at Boot

### ISSUE THREAD

**Issue by aleixsr** [NootInc/RadeonSensor#4]
**Describe the bug**
I got Kernel Panic at boot using your kexts, using older 0.3.3 works fine.

**To Reproduce**
1. Set your two kexts and boot.

**Expected behavior**
Boot with no issues

**Screenshots**
N/A

**System Information:**
 - macOS Version: [e.g. macOS 12.6.5]
 - CPU: AMD Ryzen 7 3700X (8-Core) |
- Graphics: Sapphire Pulse Radeon RX 6600 8GB GDDR6 (Navi 23)

**Additional context**
N/A

**Comment by aleixsr** [comment]
Yes I updated all of them today, do you need the list and versions?

**Comment by nanocodium** [comment]
@aleixsr bob

**Comment by nanocodium** [comment]
@nanocodium bob

**Comment by ChefKissInc** [comment]
@aleixsr Sure

**Comment by aleixsr** [comment]
> @aleixsr Sure

Loaded kexts in that order:
 - [[Kext] Lilu v1.6.6](https://github.com/acidanthera/Lilu)
 - [[Kext] VirtualSMC v1.3.2](https://github.com/acidanthera/VirtualSMC)
 - [[Kext] WhateverGreen v1.6.5](https://github.com/acidanthera/WhateverGreen)
 - [[Kext] RestrictEvents v1.1.2](https://github.com/acidanthera/RestrictEvents)
 - [[Kext] AppleALC v1.8.3](https://github.com/acidanthera/applealc)
 - [[Kext] AMDRyzenCPUPowerManagement v0.7.1](https://github.com/trulyspinach/SMCAMDProcessor)
 - [[Kext] SMCAMDProcessor v1.0](https://github.com/trulyspinach/SMCAMDProcessor)
 - [[Kext] AGPMInjector v3.3.4](https://github.com/aluveitie/AGPMInjector)
 - [[Kext] SMCRadeonGPU/RadeonSensor v0.3.3](https://github.com/NootInc/RadeonSensor) https://github.com/aluveitie/RadeonSensor
 - [[Kext] LucyRTL8125Ethernet v1.1.0](https://github.com/Mieze/LucyRTL8125Ethernet)
 - [[Kext] USB ToolBox/UTBMap-all-headers and UTBMap-no-headers (enable only 1 of these 2) v1.1.1](https://github.com/USBToolBox/kext)
 - [[Kext] AppleMCEReporterDisabler v1.0](https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip)
 - [[Kext] AirportItlwm v2.2.0](https://github.com/OpenIntelWireless/itlwm)
 - [[Kext] IntelBluetoothFirmware/IntelBTPatcher/IntelBluetoothInjector v2.3.0](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)
 - [[Kext] BlueToolFixup v2.6.7](https://github.com/acidanthera/BrcmPatchRAM)
 - [[Kext] NVMeFix v1.1.1](https://github.com/acidanthera/NVMeFix)

**Comment by ChefKissInc** [comment]
Can you please show me your config.plist entries instead of sending me an unordered list

**Comment by aleixsr** [comment]
Of course, here it is (I zipped my config.plist).
[config.000.plist.zip](https://github.com/NootInc/RadeonSensor/files/12206494/config.000.plist.zip)

**Comment by ChefKissInc** [comment]
No bug here; you have SMCRadeonGPU before RadeonSensor in your config.plist.
<img width="351" alt="Screenshot 2023-07-29 at 10 16 34" src="https://github.com/NootInc/RadeonSensor/assets/30368284/4a21b79a-5499-4c5e-8f21-a0053e3f4511">

**Comment by aleixsr** [comment]
Sorry for that, I'll test it.
By the way, where in the documentation can I found this requirement?

Thanks.

**Comment by aleixsr** [comment]
I can confirm you're right, thanks!

And please, can you show me where in the documentation this requirement is explained?

**Comment by ChefKissInc** [comment]
it's called common sense
~~also it's in the README~~

**Comment by aleixsr** [comment]
Sorry about that, my common sense doesn't understand that it worked on version 0.3.3 but it doesn't on 1.1.0.
Thanks anyway.
